image: ubuntu:18.04

stages:
    - build
    - test

before_script:
    - apt update -yqq
    - apt install -yqq build-essential
    - apt install -yqq qt5-default

build_sim:
    stage: build
    script:
        - cd source
        - qmake
        - make
    
test_sim:
    stage: test
    script:
        - cd test
        - qmake
        - make
        - make check
