image: ubuntu:18.04

stages:
    - build
    - test

before_script:
    - apt update -y
    - apt install python3-pip -y
    - pip install -U pip
    - pip install aqtinstall
    - aqt install 6.0.1 linux desktop

build_sim:
    stage: build
    script:
        - cd source/warehouseSim
        - qmake
        - make
    
test_sim:
    stage: test
    script:
        - cd test/warehouseSimTest
        - qmake
        - make
        - make check
